
spring:
  datasource:
    username: root
    password: q1hang
    url: jdbc:mysql://localhost:3306/chuyxblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 自定义数据源

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis:
  type-aliases-package: com.chuyx.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

# 开启数据库字段映射
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8088
